### ISSUE TITLE
Different datetime format for Google Takeout Youtube

### ISSUE THREAD

**Issue by mdroidian** [karlicoss/HPI#114]
My `\Takeout\My Activity\YouTube\My Activity.html` datetime shows up as `6 Oct 2020, 14:32:28 PDT`

So along with https://github.com/seanbreckenridge/HPI/commit/07e0a2dd7b5e8342df7942a090d967ea84bf7a8b I also just commented out https://github.com/karlicoss/HPI/blob/8abe66526dddf7307f2b68e28517d5531801b8a4/my/google/takeout/html.py#L18
and added `_TIME_FORMAT = "%d %b %Y, %H:%M:%S"`

I have no idea what the best way to deal with this would be, but I might look at trying at modifying `parse_dt` sometime. 😎

**Comment by karlicoss** [comment]
Ah, yeah I think this would be related too https://github.com/karlicoss/HPI/issues/103 ...

**Comment by karlicoss** [comment]
should be fixed now!
