### ISSUE TITLE
Add atexit check to core/structure to warn if there are leftover files

### ISSUE THREAD

**Issue by seanbreckenridge** [karlicoss/HPI#213]
not high priority, just seems like it'd be a good idea incase of some crash that causes the contextmanager to not remove temporarily unzipped files

**Comment by seanbreckenridge** [comment]
Is some concern with multiple HPI commands running at the same time? If something is temporarily extracted something into e.g. `/tmp/HPI-tempdir` and then you run something else while its processing, it sends the warning

Though, is still just a warning - so probably fine?

<img height="400" src="https://user-images.githubusercontent.com/7804791/153541535-48704578-cdc1-41cf-9e83-9ca9066ec375.png" />

**Comment by karlicoss** [comment]
yeah, not sure... maybe could keep pidfile or something like that in the tmp dir, but querying processes for this feels somewhat extreme :)

**Comment by seanbreckenridge** [comment]
while testing [this](https://github.com/seanbreckenridge/google_takeout_parser/commit/7b1ee8ec3c3f36e6f279f20a9a214b6a3e8775f5) in `ipdb` I did see the warning once -- i.e. the files weren't deleted

It was when I was spamming `Ctrl+C` to stop something -- so I assume the first sent the SIGINT and that started the `atexit` process, but me doing it over and over killed that regardless, leaving leftover files

**Comment by seanbreckenridge** [comment]
has been added, can open a new issue in the future if theres some more complicated strategy to be tried
