### ISSUE TITLE
Does RSS support only work with Feedbin and Feedly?

### ISSUE THREAD

**Issue by telotortium** [karlicoss/HPI#222]
Hi, I'd like to keep track of links that I've submitted to Reddit and Hacker News, and I figured I could easily automate that using their RSS feeds. However, I looked at the rss code, and it seems like it only supports Feedly and Feedbin. Is that correct?

**Comment by seanbreckenridge** [comment]
Thats correct. I have a personal module that uses [newsboat](https://newsboat.org/)

But it sounds like youre talking about using rss as a source for data, not particularly tracking what you've read -- correct?

If you want to track hackernews and reddit, could you use their respective modules instead?

https://github.com/karlicoss/HPI/blob/master/my/hackernews/dogsheep.py using https://github.com/dogsheep/hacker-news-to-sqlite

https://github.com/karlicoss/HPI/tree/master/my/reddit using https://github.com/karlicoss/rexport

That'll also likely have more info than an RSS feed

**Comment by seanbreckenridge** [comment]
Not saying some other functionality to use RSS as a data source couldn't be added -- but it would likely widely vary depending on the site, I'd assume

**Comment by seanbreckenridge** [comment]
And just to expand a bit, HPI probably wouldnt connect to a live RSS feed -- [goes against one of its core principles](https://beepb00p.xyz/tags.html#offline)

Likely, we'd create some separate tool, like `export_rss_data`, which does something like:

```
In [25]: import requests, xmltodict; data = xmltodict.parse(requests.get("https://xkcd.com/rss.xml").text)

In [26]: data['rss']['channel']['item'][0]
Out[26]: 
OrderedDict([('title', 'Consensus Time'),
             ('link', 'https://xkcd.com/2594/'),
             ('description',
              '<img src="https://imgs.xkcd.com/comics/consensus_time.png" title="Now, you may argue that the varying hour lengths and feedback effects would cause chaos. To which I say, yeah, and I\'m also curious to see how the weekday cycle interacts with it! So, you in?" alt="Now, you may argue that the varying hour lengths and feedback effects would cause chaos. To which I say, yeah, and I\'m also curious to see how the weekday cycle interacts with it! So, you in?" />'),
             ('pubDate', 'Wed, 16 Mar 2022 04:00:00 -0000'),
             ('guid', 'https://xkcd.com/2594/')])
```

saving rss feeds you give it to a file, say in `~/data/rss_data`

You'd run some cli command like `export_rss_data url1 url2 url3 --to ~/data/rss_data`, which you could put in cron or run manually, to save stuff every couple hours/daily

and then a file would be created like `my.feed.rss_data`, which can parse those files, removing any duplicates because of overlapping backups

**Comment by telotortium** [comment]
No, I'd like to use the hackernews and reddit modules. But what do you actually put in your `promnesia/config.py` file to use the `my.hackernews.dogsheep` HPI module?

**Comment by seanbreckenridge** [comment]
I think dogsheep is a relatively new module, so it doesnt have a corresponding source in promnesia yet.

Given its structure, it shouldn't be hard to add one -- can just use the [`url`](https://github.com/karlicoss/HPI/blob/e750666e30e8987f3a4c46755857dc85dd64446c/my/hackernews/dogsheep.py#L32-L42) and `permalink` attributes on the object

I think a `promnesia.sources.dogsheep` would look very similar to [something like this](https://github.com/karlicoss/promnesia/blob/master/src/promnesia/sources/smscalls.py) -- where it calls the [`dogsheep.items`](https://github.com/karlicoss/HPI/blob/e750666e30e8987f3a4c46755857dc85dd64446c/my/hackernews/dogsheep.py#L51) function, returning a visit for the permalink, and then using the `iter_urls` helper to extract any URLs from the text.

I don't use hackernews, so is a bit hard for me to write one myself, but feel free to open an issue there or create a PR [with something basic like this](https://github.com/karlicoss/promnesia/blob/master/src/promnesia/sources/smscalls.py) if you feel up to it.

**Comment by telotortium** [comment]
Thanks for the pointers - I'll add a PR for a new module when I have time.
