### ISSUE TITLE
Email history

### ISSUE THREAD

**Issue by Tmin10** [karlicoss/HPI#243]
It would be really nice to have emails history at HPI. First possible source could be google takeout mbox files. And it's also possible to add others mbox files via https://docs.python.org/3/library/mailbox.html library.
Will check and try to implement this feature.

**Comment by seanbreckenridge** [comment]
Hey, I have this implemented in my modules, you can install them alongside this repository by following instructions here:

https://github.com/seanbreckenridge/HPI#install

Have docs for setting up mail/mbox in particular:

https://github.com/seanbreckenridge/HPI/blob/master/doc/MAIL_SETUP.md

**Comment by Tmin10** [comment]
Oh, cool, I'll check it, thanks. 

Maybe there is some way to add this new features to karlicoss's HPI repo?

**Comment by seanbreckenridge** [comment]
It's possible could merge that here in the future yeah, just for the convenience

But also it doesn't need to, HPI can install both into the single namespace package, allows for people creating their own modules/repos and combining them into HPI without having to merge all the modules here

Mbox is a recent feature and not incredibly stable yet -- also want to add some spam filtering to the module but haven't got around to that yet

**Comment by Tmin10** [comment]
@seanbreckenridge thanks for explaining. Closing this issue.

**Comment by seanbreckenridge** [comment]
If you have any issues setting it up/suggestions for the module, feel free to create an issue there, is pretty barebones as a full 'email suite' right now
