### ISSUE TITLE
Document config vars to be set for different modules

### ISSUE THREAD

**Issue by Uzay-G** [karlicoss/HPI#44]
I have been starting to look at the repo and the project seems really cool but I am having major problems with configuring things. For example, in the `reddit` module. I followed the instructions by searching for where the config was needed and saw that u need to specify the `export_path` and also a `my.config.repos` object. This is not documented and it's quite unclear what this module does. I think I am not the only one with this opinion and it could be useful to document these type of configs.

Thanks for your work :)

**Comment by karlicoss** [comment]
Hi, yep, need to improve it! Started some work and there is some related discussion [here](https://github.com/karlicoss/HPI/issues/12)

Have you managed to setup the reddit module after all? Happy to help you in the meantime!

**Comment by karlicoss** [comment]
Did some experiments, and I think I managed to find a good tradeoff between the safety and the flexibility:

- https://github.com/karlicoss/HPI/pull/45/files#diff-a5a3e041f5003321bbbb6ea2831ce628R4-R8
- https://github.com/karlicoss/HPI/pull/45/files#diff-2a2beadc9249b9ca8d7bfa32bdf51818R8-R13

Will do more checks before merging, and would be nice to extract all the individual bits and generate a proper doc.

**Comment by karlicoss** [comment]
Added some initial documentation [here](https://github.com/karlicoss/HPI/blob/master/doc/MODULES.org)

**Comment by Uzay-G** [comment]
Ok thanks I understand now. I hadn't seen that it got the data from rexport but now I managed to make it work :smile:
