### ISSUE TITLE
How do I set up my.coding.github?

### ISSUE THREAD

**Issue by mreishus** [karlicoss/HPI#59]
I did the following.

- `pip install --user HPI` (python 3)
- `hpi config create`

Now inside `~/.config/my`, I have.
```
└── my
    └── config
        ├── __init__.py
        └── __pycache__
            └── __init__.cpython-38.pyc
```

(The `__init__.py` is empty and I didn't bother looking at the cache stuff).

Now I want to set up `my.coding.github`.  I went to MODULES.org but didn't see anything about coding.github.  Then I tried to read github.py.. I saw it pulls in the config, but then went a few steps out to `.export_dir`, `inputs()`, `_dal()`, `ghexport` and got lost.  How do I configure it?

**Comment by karlicoss** [comment]
Hi, thanks for trying it!
Yep, the config structure is fine (the cache files are just supplementary files Python creates in runtime, don't worry about them!

No worries, I can see it's confusing at the moment! I'll write clean up the module a bit and writegenerate documentation tomorrow, in the meantime you can set up and run the [exporter](https://github.com/karlicoss/ghexport#readme) for github data, which HPI is using as inputs.

**Comment by mreishus** [comment]
Ok, I got it to work, sorta.

- Download https://github.com/karlicoss/ghexport
- Use it to create an export json file.  Place it in /home/me/data/exports/github
- Use the github export button in settings to make a huge archive, then unzip in /home/me/data/exports/github_initial
- Make a blank cache dir /home/me/.config/my/my/config/cache

Now set up

`__init__.py`
```
class github:
    export_dir = "/home/me/data/exports/github"
    gdpr_dir = "/home/me/data/exports/github_initial"
    cache_dir = "/home/me/.config/my/my/config/cache"
```

Now I can run `python -m orger.modules.github` to make a `Github.org`.

The only issue is I ended up having to point `gdpr_dir` to a blank directory.  Apparently something in my export makes the thing crash (I guess this could be another issue if you want).

```  
File "/home/me/.local/lib/python3.8/site-packages/orger/modules/github.py", line 11, in get_items
    for e in gh.get_events():
  File "/home/me/.local/lib/python3.8/site-packages/my/coding/github.py", line 258, in get_events
    return sorted(iter_events(), key=lambda e: e.dt)
  File "/home/me/.local/lib/python3.8/site-packages/my/coding/github.py", line 258, in <lambda>
    return sorted(iter_events(), key=lambda e: e.dt)
AttributeError: 'RuntimeError' object has no attribute 'dt'
```

**Comment by karlicoss** [comment]
Right, I'm back!

Thanks for organizations example, and yeah, good job -- you figured all this out!
But I'll explain anyway:

- The `RuntimeError` thing 
    It is actually an [error handling technique](https://beepb00p.xyz/mypy-error-handling.html#kiss), but I forgot to handle it [properly](https://github.com/karlicoss/HPI/blob/a94b64c273d2347e70bdd4e280f68fcc5b3c962a/my/github/all.py#L21) during the sort. 

    The idea is that errors are propagated all the way up (instead of immediately crashing, or silently ignoring them), and downstream applications can decide what to do with them. For example, orger [now](https://github.com/karlicoss/orger/blob/c8ffb93d749cd920a93a191cd65e5ef90a728f6d/modules/github.py#L12-L14) displays it as an 'error' heading, so the user is aware when/if errors happen. I guess I'll add some flag to control error display in org-mode files -- naturally I end up with very few as I'm the developer, but I can imagine it might flood files for some people :)

As for the module itself: I [added](https://github.com/karlicoss/HPI/blob/master/doc/MODULES.org#mygithubgdpr) the docs for github modules, but will elaborate anyway:

- `cache_dir`
    You can actually keep it as `None` if you prefer, then it would just use `/tmp`. Although I'm not 100% sure this behaviour is settled -- feels like it makes more sense to mean 'caching is disabled', and to use user cache dir by default.

- `gdpr_dir`

   I added support for empty string (`''`) as path -- that way it will be simply ignored, so there won't be need for empty directory!

- `export_dir`

   I renamed to `export_path` (it's more consistent with the other modules), but the old name works too.

And in case you're curious: there are quite a few changes in https://github.com/karlicoss/HPI/pull/61 -- what I did is splitting the module into `my.github.gdpr` and `my.github.ghexport` bits. That way it's a bit more modular, makes it easier to use only one of sources if someone prefers. It's similar to the logic for twitter that I documented [before](https://github.com/karlicoss/HPI/blob/master/doc/SETUP.org#twitter). But the old `my.coding.github` is still there and should be backwards compatible.

**Comment by mreishus** [comment]
Ok, great.  Thanks for the detailed explanation and I'll give the new modules a shot when they're released.
